name: .NET

on:
  push:
    paths:
    - 'MyGarden/src/**'
    - 'MyGarden/tests/GradenAPI.Tests'
    - 'MyGarden/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from repository
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Make the script files executable
      run: | 
        cd MyGarden
        chmod +x healthcheck.sh 
    - name: Run tests
      run: |
        for project in $(find ./MyGarden/tests -name '*.Tests.csproj'); do
            dotnet test "$project"
        done

    - name: Upload test logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: MyGarden/test_logs.txt

    - name: Build and push docker containers
      run: |
        cd MyGarden
        docker compose up -d > build_logs.txt  
    - name: Upload build logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: MyGarden/build_logs.txt  

    - name: Healthcheck containers
      run: | 
        cd MyGarden
        ./healthcheck.sh postgres 120 > healthcheck_data_logs.txt 
        ./healthcheck.sh garden-api 120 >> healthcheck_data_logs.txt 
        ./healthcheck.sh auth-api 120 >> healthcheck_data_logs.txt 
        ./healthcheck.sh recognize-api 120 >> healthcheck_data_logs.txt 
        ./healthcheck.sh api-gateway 120 >> healthcheck_data_logs.txt
    - name: Upload healthcheck logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: healthcheck-logs
        path: MyGarden/healthcheck_data_logs.txt
